top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/cache
builddir     = /usr/local/src/httpd-2.4.18/modules/cache
VPATH        = /usr/local/src/httpd-2.4.18/modules/cache

include $(top_srcdir)/build/special.mk

