top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/aaa
builddir     = /usr/local/src/httpd-2.4.18/modules/aaa
VPATH        = /usr/local/src/httpd-2.4.18/modules/aaa

include $(top_srcdir)/build/special.mk

