top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/mappers
builddir     = /usr/local/src/httpd-2.4.18/modules/mappers
VPATH        = /usr/local/src/httpd-2.4.18/modules/mappers

include $(top_srcdir)/build/special.mk

