top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/server/mpm
builddir     = /usr/local/src/httpd-2.4.18/server/mpm
VPATH        = /usr/local/src/httpd-2.4.18/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
