top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/http
builddir     = /usr/local/src/httpd-2.4.18/modules/http
VPATH        = /usr/local/src/httpd-2.4.18/modules/http

include $(top_srcdir)/build/special.mk

