top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/loggers
builddir     = /usr/local/src/httpd-2.4.18/modules/loggers
VPATH        = /usr/local/src/httpd-2.4.18/modules/loggers

include $(top_srcdir)/build/special.mk

