top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/metadata
builddir     = /usr/local/src/httpd-2.4.18/modules/metadata
VPATH        = /usr/local/src/httpd-2.4.18/modules/metadata

include $(top_srcdir)/build/special.mk

