top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/filters
builddir     = /usr/local/src/httpd-2.4.18/modules/filters
VPATH        = /usr/local/src/httpd-2.4.18/modules/filters

include $(top_srcdir)/build/special.mk

