top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/core
builddir     = /usr/local/src/httpd-2.4.18/modules/core
VPATH        = /usr/local/src/httpd-2.4.18/modules/core

include $(top_srcdir)/build/special.mk

