top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules
builddir     = /usr/local/src/httpd-2.4.18/modules
VPATH        = /usr/local/src/httpd-2.4.18/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

