top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/arch/win32
builddir     = /usr/local/src/httpd-2.4.18/modules/arch/win32
VPATH        = /usr/local/src/httpd-2.4.18/modules/arch/win32
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
