top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/server/mpm/worker
builddir     = /usr/local/src/httpd-2.4.18/server/mpm/worker
VPATH        = /usr/local/src/httpd-2.4.18/server/mpm/worker

include $(top_srcdir)/build/special.mk
