top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/generators
builddir     = /usr/local/src/httpd-2.4.18/modules/generators
VPATH        = /usr/local/src/httpd-2.4.18/modules/generators

include $(top_srcdir)/build/special.mk

