top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/os/unix
builddir     = /usr/local/src/httpd-2.4.18/os/unix
VPATH        = /usr/local/src/httpd-2.4.18/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
