top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/modules/echo
builddir     = /usr/local/src/httpd-2.4.18/modules/echo
VPATH        = /usr/local/src/httpd-2.4.18/modules/echo

include $(top_srcdir)/build/special.mk

