top_srcdir   = /usr/local/src/httpd-2.4.18
top_builddir = /usr/local/src/httpd-2.4.18
srcdir       = /usr/local/src/httpd-2.4.18/os
builddir     = /usr/local/src/httpd-2.4.18/os
VPATH        = /usr/local/src/httpd-2.4.18/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
